# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: carctl

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: VERSION=1.0.0 ./build.sh

    - name: Push
      run: |
        curl -ifT carctl -u ${{ secrets.CODING_PUBLIC_REGISTRY_PROJECT_TOKEN_USERNAME }}:${{ secrets.CODING_PUBLIC_REGISTRY_PROJECT_TOKEN_PASSWORD }} \
          'https://coding-public-generic.pkg.coding.net/registry/disk/carctl/linux/amd64/carctl?version=latest'
        curl -ifT carctl -u ${{ secrets.CODING_PUBLIC_REGISTRY_PROJECT_TOKEN_USERNAME }}:${{ secrets.CODING_PUBLIC_REGISTRY_PROJECT_TOKEN_PASSWORD }} \
          'https://coding-public-generic.pkg.coding.net/registry/disk/carctl/linux/amd64/carctl?version=1.0.0'
