# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: carctl

on:
  push:
    branches: [ 'main' ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build Only
        if: "!startsWith(github.ref, 'refs/tags/')"
        run: |
          ./build.sh

      - name: Build And Push
        if: "startsWith(github.ref, 'refs/tags/')"
        run: |
          npm install coding-generic -g
          VERSION=${{ github.ref_name }} ./build.sh all
          cd ..; ls -lFh
          coding-generic -u=${{ secrets.CODING_PUBLIC_REGISTRY_PROJECT_TOKEN_USERNAME }}:${{ secrets.CODING_PUBLIC_REGISTRY_PROJECT_TOKEN_PASSWORD }} \
            --dir \
            --path=carctl/build \
            --registry="https://coding-public-generic.pkg.coding.net/registry/disk?version=${{ github.ref_name }}"

          coding-generic -u=${{ secrets.CODING_PUBLIC_REGISTRY_PROJECT_TOKEN_USERNAME }}:${{ secrets.CODING_PUBLIC_REGISTRY_PROJECT_TOKEN_PASSWORD }} \
            --dir \
            --path=carctl/build \
            --registry="https://coding-public-generic.pkg.coding.net/registry/disk?version=latest"
